### ISSUE TITLE
Add a way to verify token signature

### ISSUE THREAD

**Issue by Daniel-Houston** [okta/okta-auth-js#101]
In lib/token.js on line 231 you are calling verifyToken as follows. 
https://github.com/okta/okta-auth-js/blob/c4906a2eefc6b492b6cccb28ccc791c116c5e768/lib/token.js#L231
That last value of true sets the variable 'ignoreSignature' to true, thereby skipping the validation of the jwt signature in the verifyToken function, which parseFromUrl uses indirectly (parseFromUrl -> handleOAuthResponse -> verifyToken) My first question is what is the reasoning for always ignoring the signature of the idToken? And my second question is would you be willing to make that configurable or open to a PR that would make it configurable? 

Thanks!

**Comment by Daniel-Houston** [comment]
Anyone have any comment on this?

**Comment by Daniel-Houston** [comment]
@jmelberg-okta Sorry to pester you, but to me this issue seems more pressing than my other issue, since the id token signature is never validated. Do you have any thoughts on this one?

**Comment by jmelberg-okta** [comment]
I'm not sure of the historical reason as to why we're ignoring signature validation when receiving the `idToken` from the `/token` endpoint. IMO we should be defaulting this to `false` to ensure it gets validated.

Our team is auditing this library + making changes to ensure we have all the necessary [ID Token Validation](http://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation) steps.

Secondly, calling `token.verifyIdToken()` does validate the signature by retrieving the JWKS. You can see how it is implemented [here](https://github.com/okta/okta-auth-js/blob/73da5e0a5872f8e768fbc2064d061f1a1d5238fd/lib/token.js#L29-L93). If you're using this for Implicit flows, please use that method instead of relying on the default behavior.

I'd be happy to take a look at a PR with these changes if you have time. Please make sure to review/sign our [CLA](https://developer.okta.com/cla/) beforehand.

Thanks!

**Comment by jmelberg-okta** [comment]
Resolved with [`2.0.0`](https://github.com/okta/okta-auth-js/releases/tag/okta-auth-js-2.0.0).
