### ISSUE TITLE
Browser cache clear not handled by oauthjs 

### ISSUE THREAD

**Issue by anjalichawlaa** [okta/okta-auth-js#1210]
### Describe the feature request?

I’m using okta in React application. It is configured with authorisation code flow with refresh token. Once the user is logged in, using refresh token, new refresh token and access token are received after the expiration. But when the browser cache is cleared intentionally, local storage is removed and the application does not logout. This scenario is not handled by the oktaauthjs. For further api calls, old access token is getting used.

### New or Affected Resource(s)

Okta-auth-js

**Comment by oleksandrpravosudko-okta** [comment]
@anjalichawlaa would you mind sharing a sample code of your SDK usage?
Are you [subscribing](https://github.com/okta/okta-react/blob/master/src/Security.tsx#L69) for auth state changes in you app?

**Comment by anjalichawlaa** [comment]
@oleksandrpravosudko-okta 

Pls see the use of security component. As i'm using the security component, do I need to subscribe the authstate changes? If yes, how can I do that?
```
<Security oktaAuth={oktaAuth} restoreOriginalUri={restoreOriginalUri}>
        <Routes>
          <Route
            path="/"
            element={
              <AuthRoute>
                <HomePage />
              </AuthRoute>
            }
          />
          <Route
            path="/callback"
            element={
              <LoginCallback/>
            }
          />
        </Routes>
  </Security>
  ```
  
  I'm using react-router-dom version 6.2.1
  
```
const AuthRoute = ({ children }) => {
  const login = async (oktaAuth) => {
    const redirectLocation = window.location.pathname;
    await oktaAuth.signInWithRedirect({ originalUri: redirectLocation });
  };

  const { oktaAuth, authState } = useOktaAuth();

  if (!authState) return <img="./loading.png">;
  if (authState.isAuthenticated) {
    return children;
  } else {
    login(oktaAuth);
    return null;
  }
};

export default AuthRoute;
```

**Comment by denysoblohin-okta** [comment]
Can reproduce your issue.
Internal ref: OKTA-497664

**Comment by anjalichawlaa** [comment]
@oleksandrpravosudko-okta @denysoblohin-okta  any updates on this one?

**Comment by denysoblohin-okta** [comment]
Do you use `OktaAuth` object for making API calls you mentioned or use your HTTP client with tokens from `authState`?

Clearing storage manually is not regular user behaviour and is not handled by sync storage service.
But you can achieve behaviour you expect by adding code like this:
```
addEventListener('storage', event => {
  if (event.key === null) {
    oktaAuth.authStateManager.updateAuthState();
  }
});
```

**Comment by anjalichawlaa** [comment]
@denysoblohin-okta  I’m using tokens from authstate for api calls.

**Comment by aarongranick-okta** [comment]
@anjalichawlaa The `syncStorage` feature of the SDK is meant to keep several running tabs in sync with each other and avoid contention over the token storage. It does not provide syncing with storage which has been modified outside the SDK, such as from clearing the browser cache. Although you can add event listeners to localStorage to try and add this behavior, it is not recommended because of the potential to cause feedback loops and race conditions.  Also this technique is specific to localStorage. Imagine a classic web application with a session cookie. If you clear cookies, is it expected that the app is aware of this immediately? Or will it fail on the next request?

You mentioned that you are using the token from the authState to make API calls. This is actually not a great practice, for the reason you discovered - the API token on the authState may have been valid at the time the authState event was emitted, but may be out of date or invalid at the time you make an API call. We recommend always reading the tokens from the "source of truth" (the TokenManager) before making the API call: https://github.com/okta/okta-auth-js#tokenmanagergettokens

Ultimately, it is your backend which will validate the tokens and your app should always be prepared to receive a 40x response from your backend to signal that the session is not valid.

**Comment by aarongranick-okta** [comment]
@anjalichawlaa If you do decide to implement storage monitoring out-of-band, or otherwise know that the storage has been modified, the auth state can be updated at any time by calling `updateAuthState`
