### ISSUE TITLE
Cannot use 'in' operator to search for 'window' in undefined

### ISSUE THREAD

**Issue by rodoabad** [okta/okta-auth-js#122]
I'm getting a `Cannot use 'in' operator to search for 'window' in undefined` error on my browser. I've traced it back to https://github.com/ded/reqwest/issues/259 and one of the workarounds was to set modules to false. However, if you are using React you most likely have this turned on. Can you guys update your `reqwest` dependency?

**Comment by chuckshaw** [comment]
I'm attempting to use this client for the first time and am having the same issue:

```
Uncaught TypeError: Cannot use 'in' operator to search for 'window' in undefined
    at reqwest.js:15
    at reqwest.js:8
    at Object.<anonymous> (reqwest.js:7)
    at __webpack_require__ (bootstrap cec33e3f03e680d4b2cf:19)
    at Object._typeof (reqwestRequest.js:13)
    at __webpack_require__ (bootstrap cec33e3f03e680d4b2cf:19)
    at Object.<anonymous> (index.js:1)
    at __webpack_require__ (bootstrap cec33e3f03e680d4b2cf:19)
    at Object.<anonymous> (index.js:2)
    at __webpack_require__ (bootstrap cec33e3f03e680d4b2cf:19)
```

**Comment by jmelberg-okta** [comment]
Hi @rodoabad and @chuckshaw,

This library was designed explicitly for browser applications and has difficulties supporting:
- Server-side rendering
- Node.js

There are a couple of workarounds [described in this comment](https://github.com/okta/okta-auth-js/issues/53#issuecomment-262301224); however, our team is having discussions around extending support for the cases mentioned above in the near future.

For now, I'm going to keep this issue open and label it as an "enhancement". Sorry for the inconvenience!

**Comment by nmarshall23** [comment]
Just to add another reason to why bug in reqwest need to be addressed. 

Okta-auth-js will fail to load when building a VueJs in [Modern Mode](https://cli.vuejs.org/guide/browser-compatibility.html#modern-mode)
Because Modern browsers have decent support for native ES2015. In production ES2015 code is loaded via `<script type="module">` ES modules. A fallback is provided for older browsers. Philip Walton [details](https://philipwalton.com/articles/deploying-es2015-code-in-production-today/) how this is done.

This technique will become more common as it results in faster load times.

**Comment by manueltanzi-okta** [comment]
@rodoabad @chuckshaw @nmarshall23 

Good News! 

We released the Okta AuthN SDK as a part of the okta-auth-js library, check it out!

https://github.com/okta/okta-auth-js#node-js-usage
