### ISSUE TITLE
Is the token manager expiration event supposed to fire?

### ISSUE THREAD

**Issue by cmckni3** [okta/okta-auth-js#124]
```javascript
authClient.tokenManager.on('expired', (key, expiredToken) => {
  console.log('Token with key', key, 'has expired');
});
```

The event never fires for me even after the session has expired. I can see a request to see if the session is active in the network and receive a message along the lines of "error.errorCode: login_required, error.description: The client specified not to prompt, but the user is not logged in.".

**Comment by jmelberg-okta** [comment]
Hi @cmckni3,

Token expiration events are fired in two unique cases:
1. If [`autoRefresh`](https://github.com/okta/okta-auth-js/#can-be-in-client-configuration) is disabled
    - The background timeout has executed and the token is no longer valid.
2. If [`autoRefresh`](https://github.com/okta/okta-auth-js/#can-be-in-client-configuration) is enabled
    - The Okta session has terminated and/or is no longer active. This will throw an [`OAuthError`](https://github.com/okta/okta-auth-js/blob/master/lib/TokenManager.js#L131-L137), and emit the `expired` event.

I was successfully able to emit the token expiration event with the following code, taken from [developer.okta.com](https://developer.okta.com/code/javascript/okta_auth_sdk):

> Note: You can simulate the token expiring by updating your system clock by 1 hour (the default token lifetime)

```html
<html>
<script src="https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.8.0/okta-auth-js.min.js" type="text/javascript"></script>
<body>
  <script>
    // Bootstrap the AuthJS Client
    var authClient = new OktaAuth({
      url: 'https://{yourOktaDomain}',
      clientId: '{clientId}',
      redirectUri: '{redirectUri}'
    });
    // Attempt to retrieve ID Token from Token Manager
    var idToken = authClient.tokenManager.get('idToken');

    authClient.tokenManager.on('expired', (key, expiredToken) => {
      console.log('Token with key', key, 'has expired');
    });

    if (idToken) {
      console.log(`hi ${idToken.claims.email}!`);
    }
    else if (location.hash) {
      authClient.token.parseFromUrl()
      .then(idToken => {
        console.log(`hi ${idToken.claims.email}!`);
        // Store parsed token in Token Manager
        authClient.tokenManager.add('idToken', idToken);
        console.log(idToken);
      });
    }
    else {
      // You're not logged in, you need a sessionToken
      authClient.token.getWithRedirect({
        responseType: 'id_token'
      });
    }
  </script>
</body>
</html>
```

Want to try that out and see if the event fires? If that doesn't work, can you verify you're working off of the most recent version of `okta-auth-js`?

**Comment by cmckni3** [comment]
I am using @okta/auth-js 1.17.0 in my applications. I also tried the above code and changing the system clock without the event firing. I don't have the `Refresh Token` grant type enabled on the application.

**Comment by secretmtgdev** [comment]
Did some digging and found out the timer for expiration:

Location:     \lib\TokenManager.js
Line:            52
Code Block:
``function setExpireEventTimeout(sdk, tokenMgmtRef, key, token) {
  var clockSkew = sdk.options.maxClockSkew * 1000;
  var expireEventWait = (token.expiresAt * 1000) - (Date.now() - clockSkew);``

My okta access tokens were set to 5 minutes, but the default value on the expireEventWait was one hour.  Which was weird since that's the expiration of my ID tokens, somewhere the access token isn't being registered properly.

Sorry for my random tangent, but I hope you found this somewhat useful. I set expireEventWait to 1 & 10 seconds to test if my method would work.

My Code Block:
``
this.oktaClient.tokenManager.on('expire', (key, token) => console.log('Expired with key: ', key, ' and token: ', token))
``

**Comment by cmckni3** [comment]
Interesting. I thought the access token and id token both had a 1 hour expiration by default.

Anyways, I found the expiration never fires and appeared to be related to the event either being missed or not fired in time (going from memory, been over 6 months).
