### ISSUE TITLE
HPKP Headers in Chrome

### ISSUE THREAD

**Issue by shane-hogan** [okta/okta-auth-js#138]
On Chrome when I try and authenticate, I always get redirected back over to Oktas authentication site. 
I think it's because of HPKP headers but I can't figure out how to resolve/fix  it. 

I create a login request with

export const login = credentials => {
  return dispatch => {
    dispatch(dispatchToReducer(LOGIN));
    oktaAuth
      .signIn(credentials)
      .then(res => {
        dispatch(loginSuccess(res));
        dispatch(getGroup(res.user.id));
        dispatch(getJwt(res.sessionToken));
        dispatch(updateAll(res.user.id));
      })
      .catch(err => {
        dispatch(loginFailure( err));
      });
  };
};

And at this point I have my users info, session token, etc. So I call...

  async componentDidUpdate(prevProps) {
    if (this.props.authenticated && !prevProps.authenticated) {
      const auth = await this.props.auth;
      auth.redirect('/', { sessionToken: this.props.sessionToken });
    }
  }
I tried adding the suggested path, but that still doesn't work. It always redirects to Oktas web site.

On chromes console, there is a warning also

HTTP-Based Public Key Pinning is deprecated. Chrome 69 and later will ignore HPKP response headers. (Host: dev-xxxxxx.oktapreview.com)

Not sure if that is relevant or not

**Comment by robertjd** [comment]
Hi @shane-hogan , thanks for the questions.  The HPKP warning won't have any affect on your application.

Can you tell me more about the flow/UX you're trying to achieve?  From the above code it looks like you're using our `okta-react` and our `okta-auth-js` libraries?  If you haven't already I would take a look at our [React Sample Applications for Okta](https://github.com/okta/samples-js-react), as they show some basic flows.

If you don't need to manually use `okta-auth-js` to do primary authentication, you should be able to just use `auth.login()` in the `okta-react` library.

Let me know!

**Comment by PraJaL55** [comment]
Can you tell me more about the HPKP warning message? I am passing Auth token inside header in fetch call to my api. I get this warning every time my app makes an api call. Do I have to worry about it? Thanks in advance!

**Comment by djfdev** [comment]
I know you've said this warning won't affect my application, but is there any plan to remove it? This warning is unfortunately being seen as a defect of a product that I maintain.

**Comment by faddah** [comment]
+1, on this issue. i know it's not effecting the app, currently, but that might change as newer versions of Google Chrome come out.

At my corporation we're using the @okta/okta-react NPM package (which is https://github.com/okta/okta-oidc-js here on GitHub), and in my Google Chrome browser v73.0.3683.75 (Official Build) (64-bit), i get the following message when going to my local Dev environment of an internal web site —

```
oauthUtil.js:53 HTTP-Based Public Key Pinning is deprecated. Chrome 69 and later will ignore HPKP response headers. (Host: nike-qa.oktapreview.com)
loadFrame    @    oauthUtil.js:53
getToken    @    token.js:362
getWithoutPrompt    @    token.js:441
(anonymous)    @    util.js:67
renewToken    @    token.js:505
(anonymous)    @    util.js:67
renew    @    TokenManager.js:143
(anonymous)    @    TokenManager.js:114
promise    @    q.js:683
getAsync    @    TokenManager.js:106
(anonymous)    @    util.js:67
_callee5$    @    Auth.js:333
tryCatch    @    runtime.js:63
invoke    @    runtime.js:290
prototype.(anonymous function)    @    runtime.js:116
step    @    asyncToGenerator.js:21
(anonymous)    @    asyncToGenerator.js:39
F    @    _export.js:43
(anonymous)    @    asyncToGenerator.js:18
getAccessToken    @    Auth.js:353
_callee2$    @    Auth.js:192
tryCatch    @    runtime.js:63
invoke    @    runtime.js:290
prototype.(anonymous function)    @    runtime.js:116
step    @    asyncToGenerator.js:21
(anonymous)    @    asyncToGenerator.js:39
F    @    _export.js:43
(anonymous)    @    asyncToGenerator.js:18
isAuthenticated    @    Auth.js:220
_callee$    @    SecureRoute.js:135
Show 36 more frames
```

...so we need a fix for this also, please.

**Comment by brice-prunier-dev** [comment]
Hi,
I have the same issue on an angular app using okta-angular lib
On local (http://localhost:4200) it works well but when i deploy on an Azure WebApp using https it breaks.
It seem the redirect make a call to the server instead of rooting raising a 404 error !
It happens just after a warning on "**HTTP-Based Public Key Pinning is deprecated**"

GET https://iamapi-ngclient-dev.ase.ncd.infrasys16.com/login 404 
@ | main.a596e1b….js:1
  | e.token.getWithRedirect._setLocation | 
  | getWithRedirect | @ | main.a596e1b….js:1
  | (anonymous) | @ | main.a596e1b….js:1
  | t.loginRedirect | @ | main.a596e1b….js:1
  | (anonymous) | @ | main.a596e1b….js:1
  | e.invoke | @ | polyfills.6068544….js:1
  | onInvoke | @ | main.a596e1b….js:1
  | e.invoke | @ | polyfills.6068544….js:1
  | t.run | @ | polyfills.6068544….js:1
  | (anonymous) | @ | polyfills.6068544….js:1
  | e.invokeTask | @ | polyfills.6068544….js:1
  | onInvokeTask | @ | main.a596e1b….js:1
  | e.invokeTask | @ | polyfills.6068544….js:1
  | t.runTask | @ | polyfills.6068544….js:1
  | g | @ | polyfills.6068544….js:1
  | Promise.then (async) |   |  
  | v | @ | polyfills.6068544….js:1
  | e.scheduleTask | @ | polyfills.6068544….js:1
  | onScheduleTask | @ | polyfills.6068544….js:1
  | e.scheduleTask | @ | polyfills.6068544….js:1
  | t.scheduleTask | @ | polyfills.6068544….js:1
  | t.scheduleMicroTask | @ | polyfills.6068544….js:1
  | I | @ | polyfills.6068544….js:1
  | P | @ | polyfills.6068544….js:1
  | (anonymous) | @ | polyfills.6068544….js:1
  | (anonymous) | @ | polyfills.6068544….js:1
  | (anonymous) | @ | main.a596e1b….js:1
  | (anonymous) | @ | main.a596e1b….js:1
  | r.promiseDispatch | @ | main.a596e1b….js:1
  | (anonymous) | @ | main.a596e1b….js:1
  | u | @ | main.a596e1b….js:1
  | s | @ | main.a596e1b….js:1

**Comment by swiftone** [comment]
This is a Chrome-generated warning, not a JS error (it interrupts no JS code, it's just being triggered by JS actions), and says that Chrome will cease ENFORCING the HPKP security feature, so it also doesn't indicate a security issue.

https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning

Okta has HPKP set to report-only.  We plan to remove HPKP in the future, but it still provides some value (it is still enforced by some browsers) and does not cause problems, so the warning can be safely ignored.

**Comment by faddah** [comment]
Thank you for the response, @swiftone.
