### ISSUE TITLE
getWithRedirect is "async"

### ISSUE THREAD

**Issue by boubou158** [okta/okta-auth-js#1389]
### Describe the bug?

Hello again,

I wanted to raise of the major challenge raised while integrating the OKTA solution using the SDK.

When a getWithRedirect occurs, it will set the document.location somewhere in the sdk which will perform the redirection. The problem is that this way of redirecting is not a sync process, meaning until the url actually changes, the code of the application will continue to execute. (https://stackoverflow.com/questions/37521172/is-javascript-location-href-call-asynchronous)

Hence, it could lead to many side effects in an application to plug the authentication flow third party cookies compatible (getWithRedirect). In fact, let's assume 
- Application do some processing on some properties stored in the localStorage and delete them to set the initial state of the application

Now lets assume we plug OKTA authentication flow:
- Application will load and getWithRedirect will be triggered
- Until URL changes, application will actually start initializing the state by reading/ deleting some localStorage properties => some properties got deleted from localStorage (but valid for many other processing)
- URL changes from the previous getWithRedirect executed
- You end up back on the same application, with some properties already deleted and hence you have side effects.

Solution was to add many checks to block some processing until we are sure to be in the final redirected application. It added a lot of complexity.

Is there a clean way to fix that? I am not sure it is possible to actually do a synchronous redirection..

Thanks :)

### What is expected to happen?

NA

### What is the actual behavior?

NA

### Reproduction Steps?

NA

### SDK Versions

NA

### Execution Environment

NA

### Additional Information?

NA

**Comment by jaredperreault-okta** [comment]
Interesting observation 🤔 

Upon review I don't actually think the problem is with `getWithRedirect` being `async`. I think the problem is here ([source](https://github.com/okta/okta-auth-js/blob/4fe01df8b53435fe6935e54fbaa625242ea8a922/lib/oidc/getWithRedirect.ts#L20))
```javascript
sdk.transactionManager.save(meta);
... (irrelevant code)
window.location.assign(requestUrl);
```
`transactionManager.save` will manipulate storage, triggering storage events. As you pointed out, `window.location` (the page redirect) is really neither sync or async - sort something in between. So your app will starting responding to the storage events triggered by `tm.save` while the page redirection initiates. I'm not sure there is any good way for our SDK to handle this on behave of you application.

Some possible solutions:

- Have you storage event listeners filter out events that manipulate stored okta values, avoiding the state updates

- Update the state of your application prior to calling `getWithRedirect`, and while your in  a "`PENDING_AUTH` " state, you handle storage events differently

I think both of these options add complexity to your app (presumably the same complexity you mentioned).

I will continue to chew of this, but at first glance I'm not sure there is a clean solution

**Comment by boubou158** [comment]
Hey @jaredperreault-okta ,

I just took the example of the localStorage propertie deletion, but it is valid for any kind of not reversible logic when you refresh an application due to the redirection.

Since the redirection is not async, neither sync, and we have no way to await on it, the code of the application will keep executing until the browser actually handles the redirection. We can't predirect when this will happen. I have already noticed that depending on the browser, more code after the getWithRedirect have time to execute. (safari will have time to execute much more code before the redirection occurs than chrome or firefox for instance).

This forced us to add many flags to block some logic and added lots of complexity in the application.

Hope it clarifies :)

Thank you
