### ISSUE TITLE
TextEncoder error when use Okta on Nextjs

### ISSUE THREAD

**Issue by reinaldo-teixeira** [okta/okta-auth-js#1435]
### Describe the bug

I'm trying to use the okta lib in an internal project but when I import it into my Nextjs project it's giving this error below.

![image](https://github.com/okta/okta-auth-js/assets/101361154/5f043b21-9826-45be-8eb6-d3887ff78adb)

Would you know what it could be? I tried to import the polyfill but the error still persists.

I tried using node 16,18 and it still happens too.

### Reproduction Steps?

I installed okta in my project, and after that I generated the build using rollup and finally imported it into my nextjs project

### SDK Versions

@okta/okta-auth-js: ^7.3.0

**Comment by jaredperreault-okta** [comment]
AuthJS is an isomorphic library made to run in browser context as well as NodeJS context. This can cause some awkward behavior with SSR because your bundler will choose the browser bundle, but the browser bundle expects some globally-available APIs (like `TextEncoder` and `WebCrypto`) found in browsers.

I recommend handling auth either entirely on the client via `<NoSSR>` or `client components` (depending on what features of `NextJS` you're consuming) _or_ interface with Okta via your server and establish a traditional session with your client
