### ISSUE TITLE
fastpass authentication is not working on iOS webview

### ISSUE THREAD

**Issue by dudtjr913** [okta/okta-auth-js#1443]
### Describe the bug

I am using a webview in React Native, but fastpass authentication is not working on iOS webview. android webview is fine.
After completing fastpass authentication, the screen below appears.
I tried the solutions on [this site](https://help.okta.com/eu/en-us/Content/Topics/end-user/ov-limitations-ios.htm), but I failed.
Is it not available for use in iOS webview?

<img src="https://github.com/okta/okta-auth-js/assets/64782636/87580152-8387-469c-b467-aec670402e94" width="300" height="300">

### Reproduction Steps?

No reproduction steps

### SDK Versions

"@okta/okta-auth-js": "^7.4.0"

**Comment by mikenachbaur-okta** [comment]
Hi @dudtjr913, thank you for bringing this to our attention. You mention you're using React Native. Are you using the Okta React Native SDK? Or implementing this within your own web view?

**Comment by dudtjr913** [comment]
we are implementing Okta within a web view in our React Native app. The reason for using a web view instead of the Okta React Native SDK is that our app is composed of various services, and many of them are already built using web views. 

Since we only need Okta authentication for one particular service, it made more sense to leverage the existing web view for this purpose.

**Comment by mikenachbaur-okta** [comment]
That might be the problem @dudtjr913. Part of the workflow for FastPass is to communicate locally with the Okta Verify app itself, which might be blocked in your app due to App Transport Security (ATS) settings.  You may need to enable  exemptions for accessing services on localhost.

Many of these problems would be solved by using the Okta React Native SDK itself. Signing in using an embedded webview directly is not recommended due to security and privacy concerns. Our SDK uses Apple's ASWebAuthenticationSession to securely sign the user in, which has several benefits including improved privacy and security, and password auto-fill.

**Comment by dudtjr913** [comment]
I understand. Thanks for the reply!! ❤️
