### ISSUE TITLE
Revoke other user sessions in self service password recovery

### ISSUE THREAD

**Issue by EvilKot** [okta/okta-auth-js#1453]
### Describe the bug

Hello.

I'm struggle to find an option within self service password recovery flow to pass to trigger sessions revocation on the final step of password recovery, as listed here: https://developer.okta.com/docs/reference/api/authn/#reset-password
The only available parameter is the "password" itself.

Am i missing something? 
Thank you :3

### Reproduction Steps?

#1
```
await authClient.idx.recoverPassword({
  username: 'xxx',
  authenticators: [AuthenticatorKey.OKTA_EMAIL /* 'okta_email' */]
});
```
#2
```
await authClient.idx.proceed({ methodType: 'email' })
```
#3
```
await authClient.idx.proceed({ verificationCode: '12345' })
```
#4
```
await authClient.idx.proceed({ 
   password: 'P@ssw0rd',
   /* revokeSessions: true */
})
```

### SDK Versions

  System:
    OS: macOS 13.5
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 39.73 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.140
    Safari: 16.6
  npmPackages:
    @okta/okta-auth-js: ^7.2.0 => 7.3.0

**Comment by jaredperreault-okta** [comment]
The [documentation](https://developer.okta.com/docs/reference/api/authn/#reset-password) you linked is referencing our `authn` API. The `authn` API is made for Classic Engine.

The code references you provided are using our `idx` client, which interacts with the `idx` protocol ([reference](https://developer.okta.com/docs/concepts/interaction-code/)). The `idx` protocol is only available for Okta Identity Engine (OIE). `idx` is not truly a REST API, and therefore does not have formal documentation. It's designed to be a self-documenting, where each `remediation` describe the fields/values needed in order to proceed.

**Comment by EvilKot** [comment]
Thank you for your response!

I do understand that the provided link references another API.
However i'm struggle to find any matching counterpart in the idx, which this library covers. I've tried to find an answer by inspecting what the mentioned function (`proceed`) accepts as an input.

By your response i'm assuming that you're trying to tell that the issue is not with the library itself, but with the idx protocol itself, is that correct?

**Comment by jaredperreault-okta** [comment]
That is correct. The IDX response object will describe the fields/values needed to proceed with a remediation. The `.proceed` method will accept the input any remediation prompts for. I will check with the team that supports IDX to determine if revoking existing credentials is possible in IDX. The IDX responses are largely controlled by your org's configuration, so it's possible your IDX response will not prompt for a revoke flag, because it hasn't been enabled on your org.

**Comment by jaredperreault-okta** [comment]
Upon further review, there might be an issue with handling the `revokeSessions` value. Re-opening

Internal Ref: OKTA-645241

**Comment by EvilKot** [comment]
I really appreciate you answer. Thank you very much for giving it a closer look.
In the meantime i'll try to confirm that reset-authenticator remediation configured correctly.

**Comment by denysoblohin-okta** [comment]
@EvilKot 
`password` in auth-js IDX API is [just an alias](https://github.com/okta/okta-auth-js/blob/master/lib/idx/authenticator/OktaPassword.ts#L19) for `credentials.passcode`.
(As well as `passcode` is also alias for `credentials.passcode`)
This alias was made for convenience in IDX layer of auth-js. But it doesn't know about other options in `credentials`, so `revokeSessions` would not be even included in payload of IDX API request.

As a solution I recommend you to change
```
await authClient.idx.proceed({ 
   password: 'P@ssw0rd',
   /* revokeSessions: true */
})
```
with
```
await authClient.idx.proceed({ 
    credentials: {
        passcode: 'P@ssw0rd',
        revokeSessions: true 
    }
})
```
