### ISSUE TITLE
is cancelling transaction critical to do?

### ISSUE THREAD

**Issue by jchabotamica** [okta/okta-auth-js#1477]
### Describe the bug

Not a bug, but a question: We are building a custom login form with MFA.  I didn't see many examples of the MFA flow and trying to replicate what the widget does for the most part in regards to its calls into okta-auth-js.  I noticed it "cancels" the transaction if the customer is in the MFA flow but clicks the "back to login" button.  Is this critical?  I noticed there's multiple objects which have the cancel() function on them - they're all transaction objects and not sure how much of this we need to be concerned about. I noticed this also occurs in the "reset password" flow.

### Reproduction Steps?

Login with MFA enrolled user
Click go back to login

### SDK Versions

    @okta/okta-auth-js: ^7.4.3 => 7.4.3

**Comment by jaredperreault-okta** [comment]
Think of the transaction as the entire flow from `idx.start` to a terminal state (successful auth or unrecoverable error) and each response from `idx.proceed` (and the initial `idx.start` response) as a step within the transaction. There are times where it doesn't make sense to "go back" from the current step to the previous one

For example, A user selects `Email` authenticator then changes their mind and selects `Password`. In this case, "go back" makes sense because the user hasn't successfully challenged the selected authenticator. (A remediation will be returned in `availableSteps` to "enable" this "go back" scenario)

In the case of MFA, if a user has successfully challenged their first authenticator and is being prompted for their 2nd, it doesn't really make sense to "go back" from that point. If the user changes their mind, it probably makes more sense to abandon the current transaction

`cancel` is available on nearly every step of an IDX transaction. It essentially abandons the current transaction and starts a fresh transaction.

To answer your question, it's probably not _critical_ to include a "Back to Sign In" link (aka cancel) within your own login experience, however we try to always provide the user with an action to perform when possible, for a better UX

**Comment by jaredperreault-okta** [comment]
There is transaction metadata that is stored in storage, so abandoning the flow without calling `cancel` may cause odd behavior. But as you mentioned, there are many different ways to abandon a flow, so I wouldn't consider calling `cancel` to be _critical_

**Comment by jchabotamica** [comment]
Thanks - I will close this!
