### ISSUE TITLE
SessionToken or Okta Session Cookie

### ISSUE THREAD

**Issue by jphines57** [okta/okta-auth-js#159]
If an Okta Session is already established in a browser using the oktaAuth.getWithoutPrompt() and if you call the AuthN endpoint to get a sessionToken. If you set the sessionToken in the oktaAuth.getWithoutPrompt() but since the browser has the Okta session cookie stored, if both values are passed which one trumps the other?

When I try to implement this scenario, on the second application calls getWithoutPromt I get an Auth Error about the user not being authorized even though it does. I'm wondering if the second call is not looking at the sessionToken I'm passing in and looking at the session cookie in the header.

**Comment by aarongranick-okta** [comment]
@jphines57 I think there is some confusion here. A sessionToken is returned from the AuthN endpoint, when you login with username/password. 
`getWithoutPrompt()` is used to acquire a scoped OAuth accessToken. An error about not being authorized could have many meanings. It's possible the user does not have access to that OIDC application.
The session cookie is used only by the Okta site, and should not be used by your application.

I realize this issue is very old and probably out of date from your perspective. Please let us know if there is anything we can help you with. Thanks.
