### ISSUE TITLE
Browser issues with cookies 

### ISSUE THREAD

**Issue by AlmogRnD** [okta/okta-auth-js#215]
Hi, 
Great lib and thanks for the support, we are running into an issue which I think is core and needs to be fixed. 

User x logins into our dashboard (React.JS frontend) were using okta-auth-js everything is fine but then the user close's the browser or tab. Sometime later they come back to the dashboard they are not required to log in but when the dashboard makes an API call, for example, get user profile we get an error. 

This is happing because the Okta sign widget is saving the users token or cookie on the browser but once the user closes the browser the server token is destroyed when they open the browser back up the token or cookie on the browser is still saved but it’s outdated and used for the API call i.e. error as they don’t match anymore.  

I believe the lib should be deleting or doing its own garbage collection and if that is not possible when I run the on create method there should be a way to clear the cookies.

**Comment by swiftone** [comment]
Thanks for the feedback @AlmogRnD!   

Yours is the first report of this issue with users re-opening a browser, however I have been working with some similar issues when users are dealing with Okta sessions that have expired or been logged out of from a separate process.  (Note: All of this is only a concern during the period the local app token is still valid, not an unlimited window).

If you're curious, the issue is not so much a "bug" in code as a "bug" in shared expectations - The local app session is considered a separate session from the Okta session, but that doesn't match what all users/developers expect.  This turns a feature of OIDC - local apps don't have to have constant connections with the authorization issuer domain - into a complication.

We're currently looking at revising our explicit logout process, and I'll definitely add the use case you list to our analysis, since it impacts NON-explicit logouts as well.  Meanwhile, in terms of getting you an immediate work-around, have you tried using a promise `.catch()` on the calls that are giving you errors?  That is the current way to detect that the Okta session has ended but the local app session is still valid.

**Comment by nbarbettini** [comment]
@AlmogRnD Are you using Auth.js by itself, or our React SDK?

**Comment by AlmogRnD** [comment]
@swiftone thanks for the reply and help, the current code does not have a proper catch for all the API calls which we need to add at some point but even adding it that does not really solve the core issue. Because this is also happing if the dashboard page is open for X time, it seems that token expires even when there is an active session.

**Comment by AlmogRnD** [comment]
@nbarbettini were using create react app, and redux with Auth.js and React SDK

<img width="446" alt="Screen Shot 2019-06-07 at 10 35 13 AM" src="https://user-images.githubusercontent.com/169507/59074698-06ea2100-8910-11e9-9e43-ec785aad7f82.png">

**Comment by aarongranick-okta** [comment]
@AlmogRnD We have released several updates and fixes over the last few months, some of which may have fixed the issue. Are you still experiencing issues, or did you find a workaround?
