### ISSUE TITLE
AccessToken response inconsistent with the OIDC api reference

### ISSUE THREAD

**Issue by gunnigylfa** [okta/okta-auth-js#224]
Hi,

The access token response received when executing the `getWithoutPrompt` method returns a response of the type `okta_post_message` which looks  something like this:

``` 
{
 accessToken: "token".
 expiresAt: 1562321196, // epoch in the future
 tokenType: "Bearer",
 ...
}
```

Specifically the response includes an `expiresAt` field but the api reference for the OAuth 2.0 and OpenID Connect endpoints that Okta exposes describes the [response properties](https://developer.okta.com/docs/reference/api/oidc/#response-properties) to include `expires_in` field which returns the number of seconds until expiry.

Is there a reason why this differs? Is the Sdk using some other API under the hood? And if this is intentional is there any documentation available for those API's?

**Comment by swiftone** [comment]
> Is there a reason why this differs?

You're examining the CONTENTS of the token vs the metadata ABOUT the token (documented in the response properties).

> Is the Sdk using some other API under the hood?

No - the okta-auth-js lib is a convenience library wrapping calls to that same API.

> And if this is intentional is there any documentation available for those API's?

This isn't so much an intentional difference as an inevitable one (metadata about the token will be different than the data in the token - the token will have an unchanging `expiresAt` for example, while the `expires_in` relates to current time and thus can't live in the token itself).  

Do you have a specific need we can help you manage?
