### ISSUE TITLE
Where can I find current versions of Okta auth min js

### ISSUE THREAD

**Issue by mpGitHub** [okta/okta-auth-js#237]
I see this version out there based on another issue listed. How can I get the newer versions of this? 

All functionality w/ the token object exists when I reference this old version.
https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/2.1.0/okta-auth-js.min.js

---

The documentation mentions you can grab this out of the dist folder (I tried 2.6.1) 
and you can reference that <script> in you code, but some functionality is missing in the object after doing the new OktaAuth(... 

Ie. none of the token functionality is there

![2019-08-16_16-36-11](https://user-images.githubusercontent.com/8506767/63200326-77b36500-c046-11e9-88e4-13bdf1a8af53.png)

`If you are using the JS on a web page from the browser, you can copy the node_modules/@okta/okta-auth-js/dist contents to publicly hosted directory, and include a reference to the okta-auth-js.min.js file in a <script> tag.
`

thoughts?

**Comment by swiftone** [comment]
Hi @mpGitHub - 

The problem you're highlighting should be fixed in version 2.6.2 (2.6.3 is current as of this comment) . https://github.com/okta/okta-auth-js/blob/master/CHANGELOG.md#262

If you tried 2.6.1, you still have the bad `.min.js` file.  `npm install @okta/okta-auth-js` should get you the latest package, so you can copy the file mentioned from the /dist/ folder).  (If you have problems installing into a `node_modules` folder you may need to have a package.json in your current directory.  Consult the `npm` docs, but running `npm init -y` in a directory will give it a package.json which you can discard afterwards if you're just looking to copy the `.min.js` file.)
