### ISSUE TITLE
AuthSdkError: This browser doesn't support PKCE

### ISSUE THREAD

**Issue by patrickdemers6** [okta/okta-auth-js#242]
In my application, I am using PKCE to authenticate with Okta. When I load my SPA in Chrome I recieve the following uncaught AuthSdkError:
```
errorCauses: []
errorCode: "INTERNAL"
errorId: "INTERNAL"
errorLink: "INTERNAL"
errorSummary: "This browser doesn't support PKCE"
message: "This browser doesn't support PKCE"
name: "AuthSdkError"
```
My Chrome version is 76.0.3809.100 (Official Build) (32-bit) (cohort: Stable) and I am running node version 12.3.1. The error obviously states PKCE is not supported by my browser but why would this be? It works running on localhost but not via an IP address hostname. Is this a bug or something wrong on my end?

**Comment by mrkchang** [comment]
Does that mean that you shouldn't use PKCE if you don't want to deal with this error on Chrome?

**Comment by aarongranick-okta** [comment]
@mrkchang The most likely cause of this error is running on an HTTP (not HTTPS) domain. There is an exception for "localhost", when running & testing locally, but otherwise something like `http://yoursite.com` will fail with this error.

The Chrome flag `--unsafely-treat-insecure-origin-as-secure` can overcome this limitation locally or in testing environments. Self-signed certs are an option for local & testing using HTTPS.

We strongly recommend using end-to-end encryption in production.  If your site must run on HTTP in production, then PKCE will not work.

**Comment by jaredperreault-okta** [comment]
@AMRajapatel Please contact [support](https://support.okta.com/help/)

**Comment by pchoudhary17** [comment]
@AMRajapatel  Were you able to find any solution on this? I have the exact same issue, my app is built using reactJS and currently runs on a http based server.

**Comment by AMRajapatel** [comment]
> @AMRajapatel Were you able to find any solution on this? I have the exact same issue, my app is built using reactJS and currently runs on a http based server.

Unfortunately, no, hence we changed the API server to HTTPS

**Comment by pchoudhary17** [comment]
I was able to find a solution to this.
Instead of using Grant type to Authorization Code, I switched to Implict (Hybrid).
Using this we can pass in the pkce : false where we defien oktaAuthConfig.

I have a react app where I define this as false. responseType had also to be changed from **code** to **id_token / token**
```
const oktaAuth = new OktaAuth({
    issuer: "https://{---}.okta.com",
    clientId: "{---}",
    redirectUri: "https://{---}/oidc/callback",
    postLogoutRedirectUri: "http://{---}",
    scopes: ['openid', 'profile', 'email'],
    responseType: ["id_token", "token"],
    storageManager: localStorage,
    pkce: false,
});
```
![image](https://github.com/okta/okta-auth-js/assets/112570614/1d56f83f-9fad-4250-b679-531d900d47df)

**Comment by AMRajapatel** [comment]
Thanks for the update. I'll tryOn 22-Jan-2024 9:14 pm, Priyansh Choudhary ***@***.***> wrote:
I was able to find a solution to this.
Instead of using Grant type to Authorization Code, I switched to Implict (Hybrid).
Using this we can pass in the pkce : false where we defien oktaAuthConfig.
I have a react app where I define this as false. responseType had also to be changed from code to id_token / token
const oktaAuth = new OktaAuth({
    issuer: "https://{---}.okta.com",
    clientId: "{---}",
    redirectUri: "https://{---}/oidc/callback",
    postLogoutRedirectUri: "http://{---}",
    scopes: ['openid', 'profile', 'email'],
    responseType: ["id_token", "token"],
    storageManager: localStorage,
    pkce: false,
});

image.png (view on web)
