### ISSUE TITLE
Suggestion, detect support for TextEncoder in OktaUtils.isPKCESupported

### ISSUE THREAD

**Issue by whawker** [okta/okta-auth-js#276]
This library uses `TextEncoder` to generate a PKCE challenge

https://github.com/okta/okta-auth-js/blob/15b4552130f06c6e6d2ed68379a0d6032498026d/packages/okta-auth-js/lib/pkce.js#L62

However this [isn't supported in Microsoft Edge](https://caniuse.com/#feat=textencoder), so it errors without any useful warning (currently I see a white page with no errors in the console)

It would be handy to note that a polyfill may be required? Or perhaps extend the `isPKCESupported` method, so users can fall back to implicit flow if unsupported?

https://github.com/okta/okta-auth-js/blob/998cf3458f067a546d40a05be8b3d4719782cd18/packages/okta-auth-js/lib/browser/browser.js#L161-L167

**Comment by swiftone** [comment]
@whawker - Thanks for the report, and Yes, it would indeed be worthy detecting and otherwise improving the documentation about.  We have that in progress right now (see https://github.com/okta/okta-auth-js/pull/284#pullrequestreview-318644738 )

We avoid bundling polyfills so that we don't conflict with any bundling/polyfills you the devs might have, but we can recommend one.

**Comment by aarongranick-okta** [comment]
@whaker This behavior has been added: https://github.com/okta/okta-auth-js/pull/284
