### ISSUE TITLE
TokenManager with Async getItem and setItem

### ISSUE THREAD

**Issue by jdnichollsc** [okta/okta-auth-js#300]
Hello guys,
As you know, **localStorage** is synchronous, can we use a custom storage using async functions to get and set the token?

Thanks in advance!

**Comment by swiftone** [comment]
Thanks for the question @jdnichollsc!

While we currently support custom synchronous options (https://github.com/okta/okta-auth-js#storage ) we don't currently have an option for custom async functions.  We are in the process of reviewing our token management options and will consider this during that review (we cannot promise (ha!) to add the feature without that review because of the complexity of race conditions).

**Comment by andrewconnors** [comment]
I would love to see this happen too @swiftone. We have a use case where we're building a chrome extension and would like the storage of tokens to happen in the extension context which involves calling an async message passing function to store and retrieve tokens from the service worker. Is this on the roadmap?

**Comment by jaredperreault-okta** [comment]
@andrewconnors No, supporting async storage is not planned
