### ISSUE TITLE
cors error subdomain with wildcard

### ISSUE THREAD

**Issue by mrkchang** [okta/okta-auth-js#303]
So it looks like okta origin doesn't allow wildcard origins, and now I have the following error... Any workarounds?

 Access to XMLHttpRequest at '....' from origin '....' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by swiftone** [comment]
The CORS standard doesn't allow wildcard origins for any request with authentication.  

However, you should double check to make sure CORS is actually the issue you are encountering.  Currently, error responses on Okta services will not contain CORS headers, so you'll see a CORS error message when the real problem is whatever caused the error response on the network call.

Assuming the issue you are having is wildcard related: Because this is a web standard problem, I suggest reaching out to our support team at developers@okta.com where you can discuss your specific use-case and they can give you more specific guidance.
