### ISSUE TITLE
Angular-SSR - "Cannot read property 'getWithRedirect' of undefined"

### ISSUE THREAD

**Issue by gsaravanakumar932** [okta/okta-auth-js#344]
### Please anyone help me out to resolve such a weird. I tried in many ways i couldn't get resolved. There is not much info about this issue in OKTA forum.

> ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'getWithRedirect' of undefined
> TypeError: Cannot read property 'getWithRedirect' of undefined
>     at OktaAuthService.loginRedirect (C:\TNE\tne-qa\tne-client\dist\smartexpense\server\main.js:1:3642947)
>     at OktaAuthGuard.<anonymous> (C:\TNE\tne-qa\tne-client\dist\smartexpense\server\main.js:1:3645632)

**Simple to reproduce:
Create a new project in angular by cli commands:**

1. ng new angular-ssr
2. ng add @nguniversal/express-engine
3. npm run build:ssr
4. npm run serve:ssr

**configure your oidc configuration in Appmodule**
```
imports: [
    BrowserModule.withServerTransition({ appId: 'serverApp' }),
    OktaAuthModule.initAuth(appConfig.oidc),
    AppRoutingModule
]
```

**App Route module:** 
```
const routes: Routes = [
  {
    path: '',
    loadChildren: () =>
      import('./layout/layout.module').then(m => m.LayoutModule),
    canActivate: [OktaAuthGuard]
  },
  {
    path: 'implicit/callback',
    component: OktaCallbackComponent
  }
];
```

**Comment by gsaravanakumar932** [comment]
![getwithRedirect](https://user-images.githubusercontent.com/16773248/75848401-2911c080-5e08-11ea-9135-cf303be09283.PNG)

this is really hampering the development. Could you please help me urgent ?

**Comment by aarongranick-okta** [comment]
@gsaravanakumar932 `okta-angular` is built on the `okta-auth-js` library, which is an isomorphic node module. Since `okta-angular` only supports SPA applications we generally assume that your app is running client-side and you will be using the [webpack bundle](https://github.com/okta/okta-auth-js/blob/master/packages/okta-auth-js/package.json#L8). I think what may be happening here is that the [server-side version](https://github.com/okta/okta-auth-js#node-js-usage) of the `okta-auth-js` is being used. This version of the module is not designed to work with SPA applications and does not support the OIDC redirect flow, which involves changing the window.location.

The [OktaAuthGuard](https://github.com/okta/okta-oidc-js/tree/master/packages/okta-angular#oktaauthguard) is designed to prevent rendering of a component which requires authentication, unless the user is authenticated. If a "secure" route is loaded in an unauthenticated state it will initiate a login flow. For SPA applications, this login flow MUST occur client side. 

If you always want to perform authorization server side, you should create your Okta application as a "Web" client type. We have server-side OIDC libraries you could use, but I think that is probably not what you want.

What I am assuming you want is for only the FIRST render to occur server side, including a check of authentication state. If the user is authenticated, then the secure content is rendered. If the user is not authenticated, then some kind of loading content is rendered and a login flow will initiate as soon as the page loads on the client side.

Such a scenario is not directly supported by our SDK, but should be possible to build. One thing you would need to do is configure the TokenManager to use cookie storage so that the accessToken and idToken can be read server-side. Then you would want to provide your own route guard, similar to [OktaAuthGuard](https://github.com/okta/okta-oidc-js/blob/master/packages/okta-angular/src/okta/okta.guard.ts) but with awareness of if it is running server or client side. On client side, it can work the same as our OktaAuthGuard. On server side, it should check for presence and validity of the tokens in the cookie(s) (Unfortunately you will not be able to use any method on `okta-auth-js` server-side). However, you can use our [jwt-verifier](https://github.com/okta/okta-oidc-js/tree/master/packages/jwt-verifier) module to verify the id_token. If the token is valid, the user is logged in and you can render the "secure" content. If the token is not valid, then you should render some "loading" state and defer the login flow logic to be performed client side.

**Comment by gsaravanakumar932** [comment]
@aarongranick-okta  Thanks for your response sir. I am using SPA design pattern on client side, but the application using server side rendering technique with differential loading which is part of angular feature for performance improvement on the client side. [jwt-verifier](https://github.com/okta/okta-oidc-js/tree/master/packages/jwt-verifier) is using for doing authentication on nodeJS back end. I am using okta's implicit flow login and i followed the same steps which is provided by Okta teams sample angular application format [samples-js-angular](https://github.com/okta/samples-js-angular/tree/master/okta-hosted-login). I just changed the way of rendering the changes into SSR, but still this is client side only.

Earlier i got an error like **"Reference Error: localStorage is not defined"**, then i fixed with the package [localStorage-polyfill](https://www.npmjs.com/package/localstorage-polyfill). After that the above error, **"Cannot read property 'getWithRedirect' of undefined"** from OktaAuthGuard. I hope if it is resolved, my application would be flawless. If i remove the OktaAuthGuard, my application running smoothly. But SSO also required. We are not storing any tokens in the database. So only way is authentication through okat angular client side with the combination of SSR. 

So i need your help, how do i resolve this, what is the change that i need to do in my app? Please guide me, I referred through **"samples-js-angular"**. As you said i have my own guard also, but that would perform after the 'OktaAuthGuard' like ['OktaAuthGuard', 'AppGuard'].

Any tweek to work would be appreciable.

**Comment by aarongranick-okta** [comment]
@gsaravanakumar932 You will need to ensure that `okta-auth-js` is not instantiated server-side. You have logic to verify tokens and make the decision whether to render the route server-side, which is great, but if anything (such as the OktaAuthGuard) tries to instantiate `okta-auth-js` you will continue to run into issues, since the library should only be used client-side.  So I think you will want to avoid using OktaAuthGuard, and have your own guard be smart enough to only use `okta-auth-js` when you are on the client side, where the login flow can happen.

**Comment by gsaravanakumar932** [comment]
@aarongranick-okta I meant server side is that angular-universal. Could you please provide me some code samples would be helpful to understand. 

Because without OktaAuthGuard, the application wouldnt check for user logged in or not. 
so that i will not get the user session info. 

Angular Universal (Front End) + Back End (NodeJS + Express)

**Comment by aarongranick-okta** [comment]
@gsaravanakumar932 The logic within the guard to determine if you are authenticated is very simple: https://github.com/okta/okta-oidc-js/blob/master/packages/okta-angular/src/okta/services/okta.service.ts#L95 It is checking only for the existence of an accessToken or idToken from the TokenManager (which does some verification). 

You can do this same type of check yourself when you are rendering server-side, as long as the stored tokens are available on the server. localStorage will not be available on the server, but cookies will be. The accessToken is a standard JWT format. We provide a library (that you can use server-side) for validating access tokens: https://github.com/okta/okta-oidc-js/tree/master/packages/jwt-verifier You can use this in your guard when it is executing on the server to determine if a token is valid.

Since you will be writing a custom auth guard, I would recommend not using the `okta-angular` library, which is only a thin wrapper around `okta-auth-js`. You can borrow any useful code from it, of course. We also have a guide that shows how to build an angular app using `okta-auth-js`: https://developer.okta.com/code/angular/okta_angular_auth_js/ The results are similar to what `okta-angular` provides out of the box.

You can configure an instance of the Okta AuthJS to use cookie storage like this:
```
import OktaAuth from '@okta/okta-auth-js'
const oktaAuth = new OktaAuth({
  issuer: '...',
  clientId: '....',
  tokenManager: {
    storage: 'cookie'
  }
});
```
See the complete configuration reference here: https://github.com/okta/okta-auth-js#configuration-options

An important detail is that you should only instantiate and use Okta AuthJS when you are on the client-side. Your guard can check for an accessToken on both client and server side, but the behavior if the token is not found (or not valid) will be different server-side. 

On server side, if no valid token, you render empty/loading and send the HTML back. When the application loads on the client side it should evaluate the guard again and also see no valid token. Then it should begin a login flow, using for example [oktaAuth.token.getWithRedirect()](https://github.com/okta/okta-auth-js#tokengetwithredirectoptions)
The login will redirect to Okta for credentials and then redirect back to your login callback route. This route should have no guard on it and should have no logic on the server side. You will need to have the AuthJS library handle the callback on the client side using [oktaAuth.token.parseFromUrl()](https://github.com/okta/okta-auth-js#tokenparsefromurloptions) This method will parse the tokens from the URL and put the tokens into storage (cookies), then it will redirect to the original route which has the guard on it. 

On the client side the guard should use OktaAuth library and the TokenManager to retrieve the tokens (from the cookies) and perform verification. If they come back from the TokenManager, then you can render the protected content. (This is the same logic in `OktaAuthGuard`)

If you reload the page, your guard will execute server side. The logic there should see the tokens are present/valid and it can render the protected content and send back the HTML. 

Hopefully this makes sense. Client-side, use `okta-auth-js` and the TokenManager, configured with cookie storage.  Server-side, use `jwt-verifier` to verify existing cookies. Token cookies can only be created via client side flow.

**Comment by aarongranick-okta** [comment]
@gsaravanakumar932 In the documentation for Angular "universal server" I see there is an option to pass additional providers that only execute server-side: https://angular.io/guide/universal#universal-template-engine
Possibly you can do the `jwt-verifier` logic within a server-side provider and make the results available to your guard, so that you don't bundle any NodeJS code to be sent to the client side.

**Comment by swiftone** [comment]
Closing as it appears the question has been answered and SSR of the sign-in is out of scope for the SDK
