### ISSUE TITLE
Please support responseType option when pkce=true

### ISSUE THREAD

**Issue by zeekhoo-okta** [okta/okta-auth-js#396]
The responseType option is currently ignored when pkce=true. And both id_token and access_tokens are requested. And because id_token is being requested, hence (OIDC) scope(s) must be included in the request. 

**Background:**
With Okta, we can configure custom AuthorizationServers with any number of "default" scopes. And when we make the `/authorize` request for access_token without specifying any scopes, all the "default" scopes that were whitelisted for the requester (per *access policy rules*) are returned. This is as close as we can get to any workaround to achieving "automatic downscoping" functionality with Okta. However, Auth-JS is preventing this type of request. The alternative is to use implicit flow, or roll our own PKCE implementation.

**Comment by aarongranick-okta** [comment]
@zeekhoo-okta The `responseType` option is used on the `/authorize` request: https://developer.okta.com/docs/reference/api/oidc/#authorize

For PKCE flow, this must be set to `code`

The code returned from authorize is exchanged for token(s) using the `token` endpoint: https://developer.okta.com/docs/reference/api/oidc/#token

Here are the parameters we are passing: https://github.com/okta/okta-auth-js/blob/master/packages/okta-auth-js/lib/pkce.js#L94

If I understand your question, it seems you'd like to have fewer scopes returned to the client. We are not passing `scope` to this endpoint, so I think it may return the default scopes (as defined by the authorization server) in the access token. I think you are requesting that we pass a list of scopes (set by your app) here so that the returned token(s) are more restricted. Is this correct?

**Comment by zeekhoo-okta** [comment]
Hey Aaron. Thanks for getting back to me and sorry if the question was confusing so I'll re-state it.

Currently, Auth-JS does not allow me to specify the `responseType` when using `pkce=true`. Thus, `responseType` is always the default `['id_token', 'token']`. What I **want to do** is specify `responseType=['token']`. 

The problem is because `id_token` is being requested, then it is required to also request for scope `openid`. What I want to do is to not provide any scopes in my request. And in doing so, Okta's "magic" of automatically including all default scopes kicks in. I hope this makes sense.

**Comment by SteveMelville-fireeye** [comment]
Hi @aarongranick-okta . I am the lead architect for a CIAM project aimed at providing a unified identity solution for all of FireEye's customers and I wanted to reinforce the importance of this request. As Zee noted, **what we are asking is that the `responseType` parameter on the okta-auth-js  `token` function NOT be ignored when `pkce=true `-- i.e., make it behave the same way for both _Implicit Flow_ and _PKCE_.** 

We have a Single Page App (SPA) that is using the _PKCE_ flow (as recommended by Okta) and so, naturally want to leverage the _okta-auth-js_ library. However, due to an unfortunate behavior of Okta's core product (the lack of _downscoping_, as Zee noted and as I briefly explain below), there is no way to get BOTH an _Access Token_ with all default scopes AND an _Id Token_ from a single request. 

Here is the reason:
If _any_ scopes are included in the scope parameter on the /authorize API request, then Okta core product will ignore default scopes. And, since the only way to request an Id Token is to include `openid` as a requested scope, default scopes will not be returned on any /authorize-/token sequence that includes a request for an Id Token. The only workaround we have is to request Id tokens and Access tokens separately. But currently... the okta-auth-js library won't let us do that when `pkce=true `

Hope this makes sense. We'd love to take advantage of all of the other functionality in okta-auth-js, but need this one change to make it usable for us.

Thanks for your help on this!

**Comment by aarongranick-okta** [comment]
@zeekhoo-okta The line you pointed to does not affect what the Okta server returns to the client. As the comment says, this is "what we expect" to receive. This logic is only done to validate the response here: https://github.com/okta/okta-auth-js/blob/master/packages/okta-auth-js/lib/token.js#L300

The `/authorize` endpoint requires `responseType` to be "code" when using PKCE and the `/token` endpoint does not take a `responseType` parameter. However, both endpoints accept a `scope` parameter.

@SteveMelville-fireeye I hope I am understanding the issue correctly. 
It sounds like you want both the idToken and accessToken in a single transaction *and* you want that accessToken to contain all the default scopes as defined by the authorization server. 

You are saying that  you can get an accessToken with all default scopes if you send an empty scope to `/authorize`, however this will not return an idToken. If you add "openid" to the scope, the idToken will be returned but the accessToken will not contain all the default scopes.

Is this correct?

**Comment by SteveMelville-fireeye** [comment]
Yes. @aarongranick-okta . You've captured our desired behavior exactly.

**Comment by aarongranick-okta** [comment]
internal ref: OKTA-304898

**Comment by zeekhoo** [comment]
Hey @aarongranick-okta, thanks for being so patient. That was a huge blocker you just removed from my head. Thanks for opening the Jira. 

@SteveMelville-fireeye  - I see the catch-22 now. We CANNOT request responseType=token because it has to be responseType=code for PKCE. And Okta always returns id_token and access_token in from the `/token` endpoint (when we exchange the authorization_code for token(s)). So, there is no way to request for only the access_token if we're using authorization_code flow. 

Cheers.

**Comment by aarongranick-okta** [comment]
@zeekhoo-okta @SteveMelville-fireeye I have created a draft PR which I hope will satisfy your needs: https://github.com/okta/okta-auth-js/pull/400

This removes the assumption that an idToken will always be returned. We will assert an idToken was returned for PKCE flow only if 'openid' is in the scope.

I have made changes to the internal test app (available by running `yarn start`) to test behavior when an empty array is set for `scopes`. I see that it will return an accessToken with default scopes as defined on the authorization server. However, an idToken will not be returned on the request.

If you have already obtained an idToken or established SSO session through a normal authorization flow, you should be able to all `token.getWithoutPrompt`, `token.getWithRedirect` or `token.getWithPopup` with an empty scopes array to obtain an accessToken with default scopes.

Please let me know if this addresses your request. If so, I will move forward with code review on this PR. Thanks for bringing this to our attention!

**Comment by SteveMelville-fireeye** [comment]
@aarongranick-okta . Yep. I think that works. Basically... we make two okta-auth-js calls. The first to get the id token (signified by including `openid` in the requested scopes), and the second is to get the access token with default scopes via one of the three functions you list above.

Of course, we'd prefer not to have to make two cycles to get both tokens, but that's a problem (lack of downscoping) in the core product. So you've offered a viable work-around in the okta-auth-js library. 

Thanks for jumping on this so quickly!

**Comment by zeekhoo** [comment]
Just tested PR #400. Works! Thanks @aarongranick-okta . You can close this.

**Comment by aarongranick-okta** [comment]
@zeekhoo Glad to hear it!

**Comment by aarongranick-okta** [comment]
This has been released in version 3.1.4

**Comment by SteveMelville-fireeye** [comment]
Thanks, Aaron! Much appreciate the fast turn-around!

Regards,
Steve

**Comment by zopedope** [comment]
Hi,
I do NOT get the "default Scopes" when I try this code. I really need this functionality so I was very excited to try...

 @aarongranick-okta @zeekhoo can you please elaborate how you use `token.getWithoutPrompt` to get the Access-Token with the default scopes?

When I pass `{ scopes: [] }` the returned accessToken has no scopes.

I am using   
"@okta/okta-auth-js": "^3.1.4",
"@okta/okta-react": "^3.0.2",

Thanks 

> Just tested PR #400. Works! (Tested with token.getWithoutPrompt({ scopes: [] }))
> 
> Thanks @aarongranick-okta . You can close this.

**Comment by aarongranick-okta** [comment]
@zopedope By default, no scopes are included in the "default" set. Scopes must be set to "default" in the configuration of your authorization server. This is available under API -> Authorization Servers.

<img width="1097" alt="Screen Shot 2020-07-06 at 4 01 07 PM" src="https://user-images.githubusercontent.com/47947204/86662885-03591b80-bfa2-11ea-9cb5-645fd3135417.png">

Also be aware that `okta-react` has its own version of `okta-auth-js` in its `node_modules` folder. You probably do not need to install a 2nd copy of `okta-auth-js` and if you do it will not be used by `okta-react`. If you have done a clean install of node_modules you should have the latest version `okta-auth-js` inside `okta-react/node_modules`

**Comment by zopedope** [comment]
Thanks so much for the reply. 

I do have my scopes set as "default" and I do have the explicate install of `okta-auth-js` version 3.1.4...

```
const { code, state, tokens } = await authClient.token.getWithoutPrompt({
  scopes: [],
  responseType: ['token'],
  pkce: true
});
```

Previously if I tried to use `token.getWithoutPrompt({scopes:[]})` it would automatically add the `openid` scope... so I do think it is using the newer version of `okta-auth-js`.

<img width="527" alt="Screen Shot 2020-07-06 at 7 13 59 PM" src="https://user-images.githubusercontent.com/67662939/86664704-f4339700-bfbc-11ea-9502-f963f05fdd6a.png">

**Comment by aarongranick-okta** [comment]
@zopedope It looks like it may not be on the latest version of `okta-auth-js`, since an `idToken` was also returned. See the change here: https://github.com/okta/okta-auth-js/pull/400/files#diff-7ed8b3b03eb7b224f27f5d7972b5b921R245 Previously, an idToken would always be returned because `openid` was always added to the scopes. If the request is made with empty scopes, then ONLY the accessToken should be returned. I recommend deleting your `node_modules` directory and running `yarn` again. (If using npm instead of yarn be sure to delete your package lock file).

**Comment by zopedope** [comment]
@aarongranick-okta Basically I do an initial Login for the IdToken & AccessToken - then I use the following code to attempt to replace the AccessToken with one that will have the full set of Scopes the user can use to communicate with my API from the SPA.

So the `idToken` you see is from the initial login...

If there is a better/correct way to do this please suggest...

```
    const fetchNewScopesForUser = async ({ isAuthenticated, ...rest }) => {
      // get new accessToken with more scopes
      if (isAuthenticated) {
        var authClient = new OktaAuth({
          "clientId": "XXX",
          "issuer": "https://xxx/oauth2/default"
          , redirectUri: `${window.location.protocol}//${window.location.host}/implicit/callback`,
        });
       // tried the following too
       // const { code, state, tokens } = await authService._oktaAuth.token.getWithoutPrompt({
        const { code, state, tokens } = await authClient.token.getWithoutPrompt({
          scopes: [],
          responseType: ['token'],
          pkce: true
        });
        authService.getTokenManager().add('accessToken', tokens.accessToken);
      }
    }

    const authService = new AuthService(config.oidc)
    authService.on('authStateChange', fetchNewScopesForUser)
```

Thanks again

**Comment by zopedope** [comment]
@aarongranick-okta I hope you can show me if I'm doing something incorrect. I really want to be able to get a user's `accessToken` with the correct "Default Scopes".

1. When I use the okta.com interface I DO get my default scopes...

<img width="627" alt="Screen Shot 2020-07-07 at 11 34 06 AM" src="https://user-images.githubusercontent.com/67662939/86806558-fb06ec00-c046-11ea-9e69-cc5d61b4dfab.png">

2. But when I try with the "test app" and use the "Get Token (without prompt)" button I do not get the default scopes - just an empty list...

<img width="424" alt="Screen Shot 2020-07-07 at 11 39 19 AM" src="https://user-images.githubusercontent.com/67662939/86806580-ffcba000-c046-11ea-9640-cdf3bac7417c.png">

**Comment by zopedope** [comment]
@aarongranick-okta can you reopen this issue? I really need to be able to fetch an `accessToken` with default scopes.

Is there a different @okta package that will allow that?
