### ISSUE TITLE
SPA+PKCE = The redirectUri passed to /authorize must also be passed to /token

### ISSUE THREAD

**Issue by umerkk** [okta/okta-auth-js#398]
### I'm submitting a
  - [X] bug report
  - [ ] feature request

### Background info

When using the latest ANGULAR Okta-Signing-widget & PKCE workflow, I am getting this error in the callBackComponent "Error ‘AuthSdkError: The redirectUri passed to /authorize must also be passed to /token".

The issue persists even after assigning the redirectURI to the constructor of the widget. My Configuration is as below:
      baseUrl:  environment.oktaConfig.issuer.split('/oauth2')[0],
      clientId: environment.oktaConfig.clientId,
      redirectUri: environment.oktaConfig.redirectUri,
      authParams: {
        pkce: true,
        responseMode: 'query',
        issuer: environment.oktaConfig.issuer,
        clientId: environment.oktaConfig.clientId,
        redirectUri: environment.oktaConfig.redirectUri,
        scopes:[openid, profile, email]
      },

Although what I observed is, if I override the okta-auth-js library to V3.0.0, the code starts working fine but somehow it doesn't work with V3.1.0

This is a persistent issue.

### Your environment

  - Okta Sign-In Widget Version: 3.8.2
  - Okta auth-js: 3.1.0
  - Browser: Chrome
  - OS: Mac
  - Language: English

**Comment by swiftone** [comment]
@umerkk - We're tracking this in a few issues, so I may close this and refer you to other tickets, but the TL;DR is:
- okta-auth-js 3.1.2 should help but probably won't fix everything.
- We have an update to okta-auth-js that we hope will address everything in the works (you can look at active PRs there)
- See https://github.com/okta/okta-oidc-js/issues/744#issuecomment-642808921 for a few more details.

**Comment by aarongranick-okta** [comment]
@umerkk It's very possible that this issue is not related to the `redirectUri` but possible due to overlapping concurrent authorize requests. If you are able to debug, a breakpoint somewhere near the beginning of the authorize flow should be able to confirm if there are more than one calls being made. You may also be able to see in the network panel if there are more than one requests to /authorize being made. The call to /authorize and the call to /token must be matched exactly for the transaction to succeed, otherwise you will see this error.

**Comment by umerkk** [comment]
For that, i am using / delegating through Okta-Signin-widget and not invoking any okta-auth functions myself in the application.

**Comment by aarongranick-okta** [comment]
@umerkk Is it possible there are more than one Callback component, or more than one attempt to handle the callback? A second call to `/token` would produce this error. If possible set a breakpoint in okta-auth-js `parseFromUrl` to confirm it is not being invoked more than once on the callback. It is called from okta-angular here: https://github.com/okta/okta-oidc-js/blob/master/packages/okta-angular/src/okta/services/okta.service.ts#L199

**Comment by umerkk** [comment]
@aarongranick-okta I only have one callback component, I also created my own callback component that looks like following
  async ngOnInit() {
    return this.oktaAuth.handleAuthentication().then(() => {
      this.isAuth = true;
    })
    .catch(e => {
      let es = e;
    });
  }
I tried putting up a breakpoint and confirm that handleAuthentication is only called once.

**Comment by umerkk** [comment]
I wonder what makes it work on okta-auth-js v3.0.0

**Comment by aarongranick-okta** [comment]
@umerkk Thanks for bringing this to our attention! I was able to repro the issue using one of our sample apps and believe I understand what is happening here. The signin widget contains a bundled copy of `okta-auth-js`. Due to a change in behavior, `okta-auth-js@3.1` is not compatible with the bundled copy inside the widget. For the time being I recommend sticking with version 3.0.x while we develop a good fix for this situation.

**Comment by aarongranick-okta** [comment]
@umerkk We have released a new version of okta-auth-js (3.1.3) which should resolve this issue. Please give it a try and let us know. Thanks!

**Comment by umerkk** [comment]
@aarongranick-okta Yes, the new version works. Thanks for the quick release.
