### ISSUE TITLE
@okta/okta-auth-js/polyfill webpacking not working

### ISSUE THREAD

**Issue by SwamiKalagiri** [okta/okta-auth-js#428]
Getting `ModuleNotFoundError: Module not found: Error: Can't resolve 'core-js/fn/object/assign' in `node_modules/@okta/okta-auth-js/polyfill`

**Comment by aarongranick-okta** [comment]
@SwamiKalagiri I believe this issue is related to the specific version of `core-js` installed. It's very possibly that you have a newer version of core-js installed in your project. In newer versions, I believe it is `core-js/features/object/assign`. We will fix this in an upcoming release. In the meantime I think you should be able to work around this issue by using the prebuilt polyfill bundle which is included(bundles/okta-auth-js.polyfill.js). You can either require() this file to bundle it with your app or include it as a separate script in your HTML page

**Comment by SwamiKalagiri** [comment]
I tried to use `@okta/okta-auth-js V3.2.0`  and `core-jsV3.6.5. let me try that workaround...Thank you @aarongranick-okta for your repsonse

**Comment by aarongranick-okta** [comment]
internal ref: OKTA-347950

**Comment by shuowu** [comment]
Issue is handled in okta-auth-js-4.x.
