### ISSUE TITLE
AccessToken issued with a past expiresAt date

### ISSUE THREAD

**Issue by staffordp** [okta/okta-auth-js#430]
Was just issued a new accessToken with the 3.2 library. I noticed it has an expiresAt date with the AccessToken. The date is numeric 1595440399, but when I convert to a time such as:

`console.log(1595440399).toUTCString())`

I get the following date: Mon, 19 Jan 1970 11:10:40 GMT

The transaction object coupled with the tokens has an expiresAt date as well, but this shows "2020-07-22T16:56:17.000Z".
This seems like a huge discrepancy.  How can the token expiration be in the past 50 years ago?

What is the correct date for the token expiration?

**Comment by swiftone** [comment]
I think your example is missing some parts (as written your parens are unbalanced, console.log() returns undefined and a Number doesn't have .toUTCString(), but I can tackle your question anyway:

I believe you are running into a problem where traditional UNIX time is shown in seconds since the Epoch (Jan 1, 1970), but many languages are converting to MICROseconds since the Epoch.  

JS Date() uses microseconds since the Epoch, but JWTs use seconds since the Epoch.   `new Date(1595440399000)` (note the extra 3 0's) shows Jul 22, 2020.  Thus the JWT has the correct value, but your evaluation of that value wasn't quite the correct process.

Does that explain things?

**Comment by staffordp** [comment]
Yes, thank you.
