### ISSUE TITLE
401 Client authentication failed: /token endpoint

### ISSUE THREAD

**Issue by chrismllr** [okta/okta-auth-js#455]
Using latest version `4.0.0`. After the login via the popup succeeds, the popup closes, and a subsequent POST is made to the /tokens endpoint, returning the following error:

```js
// POST {url}/oauth2/{auth_server_id}/v1/token
{
  "error": "invalid_client"
  "error_description": "Client authentication failed. Either the client or the client credentials are invalid."
}
```

Request (although the same issue happens with getWithRedirect)
```js
client.token.getWithPopup({
  responseType: ['access_token', 'id_token'],
  scopes: ['openid', 'email'] 
});
```

Configuration used for initialization:
```json
{
  "issuer": "{url}/oauth2/{auth_server_id}",
  "url": "{url}",
  "clientId": "{client_id}"
}
```

This is very possibly a configuration error on the Okta side, but I'm looking for any direction to debug at this point.

**Comment by swiftone** [comment]
Hi @chrismllr - Thanks for the report, let me see if I can replicate this and get back to you.

**Comment by swiftone** [comment]
@chrismllr - I couldn't replicate your issue with things configured correctly, but someone else (Thanks @aarongranick-okta !) noticed this error can happen if you're using a "Web app" (intended for a backend server) instead of a "SPA app" as the source of your client Id.

I suggest checking to see if that is happening and let us know if that helps.

One quick note: the `url` param is no longer used after version 2.x, see https://github.com/okta/okta-auth-js#from-2x-to-3x.   I did run a check with it included and it made no difference.  I also confirmed that blocking 3rd party cookies did not result in your error.

**Comment by chrismllr** [comment]
Wonderful -- I'll attempt switching to SPA today and report back.

And noted on the url param. I'm upgrading from 2.13.0, so working through the minor differences 👍

**Comment by chrismllr** [comment]
@swiftone That was it -- SPA did the trick 🎉 

Might be helpful to add this into the "Need Help" section of the docs? Or some prerequisite setup -- unless this is covered somewhere else and I missed it!

Thanks again for the quick response, and for the assist @aarongranick-okta

**Comment by chrismllr** [comment]
Not sure if its the correct place for the docs or if it seems useful, but took a stab at adding some troubleshooting docs:

https://github.com/okta/okta-auth-js/pull/456
