### ISSUE TITLE
Add support for Node

### ISSUE THREAD

**Issue by jeharder** [okta/okta-auth-js#53]
I get this when trying to start my node app. Not sure where to go from here.

/home/ubuntu/node_modules/@okta/okta-auth-js/lib/http.js:9
var httpCache = storageBuilder(localStorage, config.CACHE_STORAGE_NAME);
                               ^
ReferenceError: localStorage is not defined

**Comment by rchild-okta** [comment]
Hi @jeharder - We haven't explicitly added Node support yet (AuthJs is currently client-side only). I've added this as a feature request on our end to look into. There are currently some browser-based assumptions that we'll need to fix - generic storage (instead of requiring localStorage), a node specific request library, and adding in an option to pass in an apiKey.

In the meantime, it might be possible to work around these issues by polyfilling what we're doing (although it would probably require digging into the code). Some ideas:
- Use [rewire](https://www.npmjs.com/package/rewire) or node [global](https://nodejs.org/api/globals.html#globals_global) to polyfill localStorage. This is not good practice in general, but unfortunately we've hardcoded the assumption that localStorage is available.
- For requests, it's possible to override our request library (by default, jquery). There's an example here with [reqwest](https://github.com/okta/okta-auth-js/tree/master/reqwest). For node, you'd probably want to do something like this, but use [none](https://github.com/okta/okta-auth-js/tree/master/none) and pass in a wrapper around the node request lib.
- For the apiKey, you can pass in `headers` when initializing AuthJs.

**Comment by omgitstom** [comment]
We should probably be explicit about this in the readme

**Comment by Mark-McCracken** [comment]
Has any progress been made on this issue?
Would be great to have a those few small tweaks made, and an example to go with it for Node interactions with Okta

**Comment by jameshowe** [comment]
Would be good to get an official update on this, migrating from Stormpath having no readily available NodeJS lib is a bit of a setback, would also be good to hear if there is any plans to keep the node version separate or have it integrated into https://github.com/okta/okta-sdk-nodejs.

**Comment by mraible** [comment]
It would be very cool if we could use the Auth SDK with frameworks like Nuxt.js and Angular Universal. I tried today and encountered the following error (using Nuxt.js).

![auth-sdk-window-not-defined](https://user-images.githubusercontent.com/17892/30300429-d1c4fc30-9711-11e7-8513-ca30088e6ba5.png)

**Comment by manueltanzi-okta** [comment]
@jeharder @Mark-McCracken @jameshowe

Good News! 

We released the Okta AuthN SDK as a part of the okta-auth-js library, check it out!

https://github.com/okta/okta-auth-js#node-js-usage
