### ISSUE TITLE
Microsoft Issue

### ISSUE THREAD

**Issue by nayefmhmd85** [okta/okta-auth-js#556]
Can I use this library with Microsoft Auth also ????

**Comment by swiftone** [comment]
@nayefmhmd85 - Thanks for the question.  Unfortunately, I'm not sure what you mean by "Microsoft Auth", as MS has a lot of authentication options, libraries, and tools.  Can you share some more details about what you are trying?

**Comment by nayefmhmd85** [comment]
thnx a lot for your response

**Comment by nayefmhmd85** [comment]
Iam making Electron project  with react ,
in my project I use Hash Router which is file based , Not route based 
I used MsalJs 
but when I build My app to release MsalJs not work because there is no Http

**Comment by nayefmhmd85** [comment]
So My Question is ,
Is this SDK support Microsoft Login , as Google , I mean Third Party Auth (OpenAuth)

**Comment by swiftone** [comment]
You're using some libraries I haven't, so I may not be understanding your situation correctly, but I think these are some answers:

okta-auth-js (this library) is specific to authentication using Okta.  Okta supports numerous identity providers, but this library is only for authenticating with Okta itself.  

Electron is not part of our test suite, so I don't know if this library has any issues with it, but this library assumes a live internet connection for use and wouldn't work "offline".

This library can work with HashRouting, but it does take some additional effort because OAuth2 redirects cannot contain hash fragments per the Oauth2 specification.

I hope that helps
