### ISSUE TITLE
AuthSdkError: Unable to parse a token from the url (works with IP address, not domain name)

### ISSUE THREAD

**Issue by mfickett** [okta/okta-auth-js#570]
I'm seeing the same behavior as [this dev forum post](https://devforum.okta.com/t/authsdkerror-unable-to-parse-a-token-from-the-url/996) describes.

When I access my app at `http://myapp.company.cloud:8080/` it does not work, I get `AuthSdkError: Unable to parse a token from the url`. But when I use `http://10.1.2.3:8080` authentication works. (And then if I go back to the domain name version that will then load.)

I'm currently serving without SSL due to other constraints.

My client config for a Vue.js SPA is:
```
const oktaConfig = {
  clientId: VUE_APP_OKTA_CLIENT_ID,
  issuer: VUE_APP_OKTA_ISSUER_DOMAIN,
  redirectUri: `${document.location.origin}${LOGIN_CALLBACK_PATH}`,
  // Okta recommends setting cookies.secure=false when not serving over HTTPS.
  cookies: { secure: false },
  // PKCE is the default and avoids tokens in URLs, but cannot be used without HTTPS.
  // Use the implicit flow instead.
  pkce: false
};
```

My app has:

* Application type: Single Page App
* Allowed grant types: not Authorization Code, yes Implicit, yes Allow ID Token and yes Allow Access Token
* login redirect URIs and logout redirect URIs for both IP address and domain

**Comment by swiftone** [comment]
@mfickett - Thanks for the report.  As you can see on the forum post you link to, the situation you describe is a puzzle to us, so there must be some factor we've not yet identified.

First, you likely already know this, but let me put in for posterity and anyone else reading:   Okta does not recommend using HTTP instead of HTTPS, nor setting cookies.secure to false, for any production code.  

Moving past that:

Can you look at the Network Dev Tools in the browser (with "Preserve Log", or whatever your browser calls that, so that we don't lose history over redirects) and share the list of endpoints and status codes you see?  My best wild guess is that there's a redirect involved that is losing essential information, but I want to confirm before digging into that theory any deeper.

**Comment by aarongranick-okta** [comment]
@mfickett Have you checked your "Trusted Origins" settings? (Admin -> Security -> API -> Trusted Origins). This should be set for every domain that your app is running on.

If that doesn't work, my next question is if you get the same result in all browsers, or is it specific to one browser? (We have seen some issues with Safari and the implicit flow, could be relevant if it affects Safari and not Firefox/Chrome).

**Comment by mfickett** [comment]
I can't reproduce the error now, either in an incognito window, or after clearing all my `*okta*` and `*myapp*` cookies. (Confirmed that my config is as posted in the original description.)

I'm using Chrome Version 87.0.4280.67 (Official Build) (x86_64) on MacOS 11.0.1 (Big Sur).

I'll close this now but reopen and provide a network history if I can get it to happen again.

Thanks for taking a look!
