### ISSUE TITLE
Help: How to set the date of idtoken expires.

### ISSUE THREAD

**Issue by arvin-yao** [okta/okta-auth-js#581]

**Comment by shuowu** [comment]
@arvin-yao The following thread may help https://support.okta.com/help/s/question/0D51Y00006CHjMz/how-can-you-adjust-the-expiration-date-of-a-jwt-token?language=en_US

**Comment by askouras** [comment]
To tag onto what @shuowu is saying, ID tokens by default have a one hour lifetime, but you can use a Token Inline Hook (A custom authorization server is required to use this) to [modify the ID token lifetime](https://developer.okta.com/docs/reference/token-hook/#sample-response-to-modify-token-lifetime) to as little as 5 minutes (which is the lowest you can set an Access Token lifetime to with an [Access Rule](https://developer.okta.com/docs/guides/customize-authz-server/create-rules-for-policy/) for a custom authorization server. 

Again, keep in mind that a Custom Authorization Server must be available to use for this to be an option, otherwise the default one hour lifetime applies.
