### ISSUE TITLE
Add support for Authorization Code Flow

### ISSUE THREAD

**Issue by spawnrider** [okta/okta-auth-js#78]
I need to implement the **Authorization Code flow** in a professional app which is using Okta, Okta verify, [PKCE ](https://tools.ietf.org/html/rfc7636), and the Authorization Code Flow.

The **okta-auth-js** library does not actually allows to retrieve a code from a client id and a challenge.

**Comment by lboyette-okta** [comment]
It doesn't support the auth code flow because `okta-auth-js` is a client side library, so it's not designed to receive a code (outside of a hybrid flow that passes the code to the server).

It's *technically* possible to do PKCE in the browser, but it's almost always used for mobile apps.

Why would you like to use PKCE in the browser?

**Comment by spawnrider** [comment]
It's for an mobile hybrid application developed using Ionic. 
This application is an mobile app but eun into a local browser.

**Comment by spawnrider** [comment]
For me, it's 2 different kind of issues. 
1. I am using PKCE in order to retrieve the authorization code without exposing a secret in my app (only using client_id).
2. I am retrieving access token / refresh token using this method from the token endpoint. So I also want to have silent / automatic access token refresh using the refresh token.

Maybe It's not the right way to do it...

**Comment by jmelberg-okta** [comment]
Hey @spawnrider,

This is why the Implicit flow is encouraged for these types of applications. It allows you to return OAuth/OpenID Connect tokens as a **public client**.

Our library leverages a user's session in Okta to keep the token active behind-the scenes (see [`autoRefresh`](https://github.com/okta/okta-auth-js/#the-tokenmanager)), so a refresh token isn't needed. While using the PKCE flow will grant you the ability to have a **refresh token**, you're opening up your application to a number of [attack vectors](https://tools.ietf.org/html/rfc6819#section-4.1.2).

Closing down this issue as a "wont fix", because of the security implications it could cause for library users.

**Comment by reste85** [comment]
Hi all, and sorry for commenting this closed issue. 
What about the new draft from IETF which states to use authorization code flow with PKCE instead of implicit flow?
Here's the link:
https://tools.ietf.org/id/draft-parecki-oauth-browser-based-apps-02.txt

thank you!

**Comment by GaTechThomas** [comment]
I'm not sorry for commenting on a closed post...

Can we please get a response to the previous comment?

**Comment by jmelberg-okta** [comment]
Apologies for not posting here sooner, but this feature is under [active development](https://github.com/okta/okta-auth-js/pull/205) for this library.

We will update the status of this issue, along with provide instructions in our [release notes](https://github.com/okta/okta-auth-js/releases) when this feature ships.

Thanks!

**Comment by GaTechThomas** [comment]
It seems that Okta is shutting down this conversation because the client library doesn't solve all attack vectors. It never will. There will always need to be mitigations. Developers working in a security domain will always need to understand what they're doing beyond simply including a library and calling it a day. 

That said, we need these libraries to support the recommendations.

Please direct us to a viable Okta recommendation that is in line with the standards recommendation.

**Comment by nbarbettini** [comment]
@GaTechThomas I agree, it's important to understand how the security works and what risks exist. The new guidance from the OAuth working group reflects the fact that, while there aren't any _new_ vulnerabilities or problems with the implicit flow, it was always a compromise. Now there's a better way (PKCE).

This blog post covers more background and demonstrates how to use the authorization code + PKCE flow with Okta today, if you want: https://developer.okta.com/blog/2019/05/01/is-the-oauth-implicit-flow-dead
You'll soon see updates to all of our JS libraries to reflect the new guidance. If you have questions or concerns, feel free to keep posting here, or you can email me directly at nate.barbettini@okta.com.

**Comment by GaTechThomas** [comment]
Thank you for the follow ups! This will be very helpful for a project that we're just starting.

**Comment by swiftone** [comment]
Support for Authorization Code Flow with PKCE has been previously added to auth-js, okta-react, okta-angular, and okta-vue.  See the README files for those packages and related guides on developer.okta.com for details.

Closing this issue.
