### ISSUE TITLE
Missing Identity Provider parameter?

### ISSUE THREAD

**Issue by rsotolongo** [okta/okta-auth-js#899]
I was using library “okta-angular” v3.1.0 that depends on library “okta-auth-js” v4.8.0. Specifically calling the method “OktaAuthService.signInWithRedirect” passing an object of type “SigninWithRedirectOptions” which have a property “idp” accepting the Okta Identity Provider Identifier, so Okta redirects to that IdP at the time to authenticate.

OktaAuthService.signInWithRedirect({ idp: “1234567890” });

After update “okta-angular” to latest version 3.2.2, now it depends on “okta-auth-js” v5.2.3 where “SigninWithRedirectOptions” changed dramatically and don’t have the idp parameter anymore. My question is, how to pass the Identity Provider Identifier to start the signing process using an external configured IdP?

**Comment by shuowu** [comment]
@rsotolongo OktaAuthService extends OktaAuth, and the signature of the `oktaAuth.signInWithRedirect` should not been changed. It should still work with all the [token params](https://github.com/okta/okta-auth-js#authorize-options). 

I think the issue you are facing right now is because of a type bug that was introduced in okta-auth-js 5.x. Can you disable the type checking for `signInWithRedirect` as a workaround while we are working on the fix.

Internal Ref: OKTA-419412

**Comment by rsotolongo** [comment]
Thank you for the response. I disabled the type checking as a temporary solution. There is a public ticket (bug number, etc.) to follow-up and know once this issue is resolved?

**Comment by shuowu** [comment]
@rsotolongo We will update in this Github thread.

**Comment by rsotolongo** [comment]
Thank you...

**Comment by shuowu** [comment]
Released in [5.7.0](https://github.com/okta/okta-auth-js/releases/tag/okta-auth-js-5.7.0)
