### ISSUE TITLE
Resending SMS after enrolling throws exception

### ISSUE THREAD

**Issue by Connor-Knabe** [okta/okta-auth-js#90]
When enrolling SMS as factor using .enroll() on transaction and then trying to resend SMS using .resend() on response object throws an exception:
> AuthSdkError('No link found for that name');
> throw new AuthSdkError('Must provide a link name');

Is there something I'm missing? For the others, we don't have to specify a link

**Comment by lboyette-okta** [comment]
`okta-auth-js` simply converts any authentication response into a transaction by creating methods based on the `_links` returned in the Authn API. We've tried to document as much of this as we can in the `README`, but it looks like we missed this one.

I'm guessing you're in the `MFA_ENROLL_ACTIVATE` status, so the response [looks like this](https://developer.okta.com/docs/api/resources/authn.html#response-example-for-enroll-okta-sms-factor). In the case, `resend` is an array (presumably you could also resend an `email` or something else). Most of the time, `resend` returns an object instead of an array, so you don't have to select by name. Because there are multiple options in this case, we'll need the name.

```javascript
transaction.resend('sms')
```

We'll include this info in the docs.

**Comment by Connor-Knabe** [comment]
@lboyette-okta ok great thank you for the clarification!
